export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_PROFILE_PICTURE = "SET_PROFILE_PICTURE";
export const FETCH_ROSTER_SUCCESS = "FETCH_ROSTER_SUCCESS";
export const ADD_ROSTER_ITEM_SUCCESS = "ADD_ROSTER_ITEM_SUCCESS";
export const UPDATE_ROSTER_ITEM_SUCCESS = "UPDATE_ROSTER_ITEM_SUCCESS";
export const DELETE_ROSTER_ITEM_SUCCESS = "DELETE_ROSTER_ITEM_SUCCESS";
